import "dotenv/config";
import { drizzle } from "drizzle-orm/postgres-js";
import { eq } from "drizzle-orm";
import postgres from "postgres";
import * as schema from "../src/lib/db/schema";

/**
 * Seeds realistic demo data: categories, products, a demo business +
 * its customers/campaigns/insights. Run with `npm run db:seed` after
 * `npm run db:push`. Safe to re-run — categories/products are keyed
 * by unique name, and existing products are updated without losing data.
 */

const BUSINESS_OWNER_EMAIL = process.env.SEED_BUSINESS_EMAIL || "business@demo.com";

interface ProductSeedItem {
  name: string;
  cat: string;
  brand: string;
  price: number;
  mrp: number;
  rating: number;
  reviewCount: number;
  stock: number;
  tags: string[];
  images: string[];
  description?: string;
  specifications?: Record<string, string>;
}

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL is required to seed.");
  const sql = postgres(connectionString, { prepare: false });
  const db = drizzle(sql, { schema });

  console.log("Seeding categories...");
  const categoryDefs = [
    { name: "Laptops", icon: "💻" },
    { name: "Smartphones", icon: "📱" },
    { name: "Headphones", icon: "🎧" },
    { name: "Watches", icon: "⌚" },
    { name: "Shoes", icon: "👟" },
    { name: "Cameras", icon: "📷" },
    { name: "Backpacks", icon: "🎒" },
    { name: "Accessories", icon: "🔌" },
  ];
  const categoryIds: Record<string, string> = {};
  for (const c of categoryDefs) {
    const slug = c.name.toLowerCase();
    const [row] = await db.insert(schema.categories).values({ name: c.name, icon: c.icon, slug })
      .onConflictDoUpdate({ target: schema.categories.name, set: { icon: c.icon } })
      .returning();
    categoryIds[c.name] = row.id;
  }

  console.log("Looking up (or creating) the demo business...");
  const existingUser = await db.query.users.findFirst({ where: (u, { eq }) => eq(u.email, BUSINESS_OWNER_EMAIL) });
  let businessId: string | undefined;
  if (existingUser) {
    const business = await db.query.businesses.findFirst({ where: (b, { eq }) => eq(b.ownerId, existingUser.id) });
    businessId = business?.id;
  }
  if (!businessId) {
    const anyBusiness = await db.query.businesses.findFirst();
    if (anyBusiness) {
      businessId = anyBusiness.id;
      console.log(`Using existing business "${anyBusiness.storeName}" (${businessId}) for demo data.`);
    } else {
      console.log(
        `No business found for ${BUSINESS_OWNER_EMAIL} yet. Products will be seeded without an owning business.\n` +
        `Sign up as a business account first, then re-run this script to attach real ownership.`
      );
    }
  }

  console.log("Seeding / updating products...");
  const PRODUCTS: ProductSeedItem[] = [
    /* ============================================================
       1. LAPTOPS (16 Products)
       ============================================================ */
    {
      name: 'NovaBook Pro 14"',
      cat: "Laptops",
      brand: "Nova",
      price: 76999,
      mrp: 89999,
      rating: 4.7,
      reviewCount: 412,
      stock: 18,
      tags: ["video editing", "16GB RAM", "SSD", "ultrabook"],
      images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80"],
      description: 'NovaBook Pro 14" delivers ultra-fast M-series computing with a vibrant 120Hz Liquid Retina display and 18-hour all-day battery life.',
      specifications: { "Display": '14.2" Liquid Retina 120Hz', "Processor": "Octa-Core Pro Chip", "RAM": "16GB Unified", "Storage": "512GB NVMe SSD", "Battery": "Up to 18 hours" },
    },
    {
      name: 'AeroBook Air 13"',
      cat: "Laptops",
      brand: "Aero",
      price: 54999,
      mrp: 61999,
      rating: 4.4,
      reviewCount: 289,
      stock: 32,
      tags: ["lightweight", "student", "portable", "silent"],
      images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80"],
      description: 'AeroBook Air 13" is feather-light at 1.2kg with a fanless silent design, crystal-clear 2K display, and 15-hour battery built for students and commuters.',
      specifications: { "Display": '13.3" IPS 2K', "Processor": "Quad-Core Ultra Low Power", "RAM": "8GB LPDDR5", "Storage": "256GB SSD", "Weight": "1.24 kg" },
    },
    {
      name: "TitanForce G15 Gaming",
      cat: "Laptops",
      brand: "Titan",
      price: 98999,
      mrp: 112999,
      rating: 4.6,
      reviewCount: 150,
      stock: 9,
      tags: ["gaming", "RTX", "high performance", "144Hz"],
      images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80"],
      description: "TitanForce G15 brings uncompromising AAA gaming performance featuring NVIDIA RTX 4070 graphics, 165Hz IPS display, and dual-fan liquid cooling.",
      specifications: { "Display": '15.6" FHD 165Hz 100% sRGB', "Processor": "Intel Core i7-13700H", "GPU": "NVIDIA RTX 4070 8GB", "RAM": "16GB DDR5 5200MHz", "Storage": "1TB Gen4 SSD" },
    },
    {
      name: 'ZenMaster Studio 16 OLED',
      cat: "Laptops",
      brand: "ZenMaster",
      price: 119999,
      mrp: 134999,
      rating: 4.8,
      reviewCount: 94,
      stock: 14,
      tags: ["video editing", "OLED", "creator", "4K"],
      images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80"],
      description: "ZenMaster Studio 16 is the ultimate creative workstation with a color-calibrated 4K OLED touch panel, dial controller, and RTX studio drivers.",
      specifications: { "Display": '16.0" 4K OLED HDR 500 nits', "Processor": "Intel Core i9-13900H", "GPU": "NVIDIA RTX 4060 8GB", "RAM": "32GB DDR5", "Storage": "1TB NVMe SSD" },
    },
    {
      name: "Helix Flex 2-in-1 Touch",
      cat: "Laptops",
      brand: "Helix",
      price: 64999,
      mrp: 72999,
      rating: 4.5,
      reviewCount: 178,
      stock: 22,
      tags: ["touchscreen", "convertible", "stylus", "portable"],
      images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80"],
      description: "Helix Flex 360-degree convertible laptop transforms effortlessly from a laptop into a drawing tablet with bundled active pressure stylus.",
      specifications: { "Display": '14.0" FHD+ Touch 360°', "Processor": "AMD Ryzen 7 7730U", "RAM": "16GB LPDDR4X", "Storage": "512GB SSD", "Stylus": "Active Pen Included" },
    },
    {
      name: "EdgeBook Ultra 14 Carbon",
      cat: "Laptops",
      brand: "EdgeBook",
      price: 84999,
      mrp: 96999,
      rating: 4.7,
      reviewCount: 205,
      stock: 16,
      tags: ["business", "carbon fiber", "lightweight", "thunderbolt"],
      images: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80"],
      description: "Crafted from aerospace-grade carbon fiber, EdgeBook Ultra weighs under 1.1kg with military-grade durability and hardware TPM security.",
      specifications: { "Display": '14.0" 2.8K IPS 400 nits', "Processor": "Intel Core i7-1360P", "RAM": "16GB LPDDR5", "Storage": "512GB Gen4 SSD", "Weight": "1.08 kg" },
    },
    {
      name: "PulseBook Slim 15",
      cat: "Laptops",
      brand: "Pulse",
      price: 42999,
      mrp: 49999,
      rating: 4.3,
      reviewCount: 520,
      stock: 45,
      tags: ["budget", "student", "home office", "numeric keypad"],
      images: ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80"],
      description: "PulseBook Slim 15 offers dependable day-to-day computing for office and studies with a full-size backlit keyboard and anti-glare display.",
      specifications: { "Display": '15.6" FHD Anti-glare', "Processor": "AMD Ryzen 5 5500U", "RAM": "8GB DDR4 (Expandable)", "Storage": "512GB SSD", "Battery": "45Wh Fast Charge" },
    },
    {
      name: "CyberByte Stealth RTX 4080",
      cat: "Laptops",
      brand: "CyberByte",
      price: 164999,
      mrp: 189999,
      rating: 4.9,
      reviewCount: 68,
      stock: 7,
      tags: ["gaming", "RTX 4080", "esports", "RGB"],
      images: ["https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=800&q=80"],
      description: "Flagship gaming rig engineered with vapor chamber cooling, mechanical per-key RGB keyboard, and desktop-class RTX 4080 GPU.",
      specifications: { "Display": '17.3" QHD 240Hz G-Sync', "Processor": "Intel Core i9-13980HX", "GPU": "NVIDIA RTX 4080 12GB", "RAM": "32GB DDR5 5600MHz", "Storage": "2TB Gen4 SSD" },
    },
    {
      name: "InfinityBook Creator 16X",
      cat: "Laptops",
      brand: "Infinity",
      price: 104999,
      mrp: 118999,
      rating: 4.6,
      reviewCount: 112,
      stock: 12,
      tags: ["creator", "3D modeling", "color accurate", "DCI-P3"],
      images: ["https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80"],
      description: "Calibrated for photography and color grading with 100% DCI-P3 color gamut, SD Express card slot, and whisper-quiet dual fans.",
      specifications: { "Display": '16.0" 3.2K 120Hz Calman-Verified', "Processor": "AMD Ryzen 9 7940HS", "GPU": "RTX 4050 6GB", "RAM": "32GB LPDDR5X", "Storage": "1TB NVMe SSD" },
    },
    {
      name: "SwiftAir Go 14",
      cat: "Laptops",
      brand: "SwiftAir",
      price: 49999,
      mrp: 57999,
      rating: 4.4,
      reviewCount: 310,
      stock: 28,
      tags: ["lightweight", "productivity", "fast charge", "type-c"],
      images: ["https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=800&q=80"],
      description: "Sleek all-aluminum body with fast USB-C PD 65W charging and fingerprint login for modern professionals on the move.",
      specifications: { "Display": '14.0" IPS 100% sRGB', "Processor": "Intel Core i5-1335U", "RAM": "16GB LPDDR5", "Storage": "512GB SSD", "Weight": "1.25 kg" },
    },
    {
      name: "WorkStation Pro 17 Max",
      cat: "Laptops",
      brand: "Nova",
      price: 145999,
      mrp: 169999,
      rating: 4.8,
      reviewCount: 82,
      stock: 6,
      tags: ["workstation", "CAD", "enterprise", "ECC memory"],
      images: ["https://images.unsplash.com/photo-1588702547919-26089e690ecc?auto=format&fit=crop&w=800&q=80"],
      description: "Certified workstation powerhouse optimized for CAD modeling, architectural rendering, and heavy parallel simulations.",
      specifications: { "Display": '17.0" 4K IPS Anti-Glare', "Processor": "Intel Core i9-13900HX", "GPU": "NVIDIA RTX A2000 8GB", "RAM": "64GB DDR5 ECC", "Storage": "2TB NVMe SSD" },
    },
    {
      name: "AuraBook Neo 13 Retina",
      cat: "Laptops",
      brand: "Aura",
      price: 68999,
      mrp: 77999,
      rating: 4.5,
      reviewCount: 165,
      stock: 19,
      tags: ["retina display", "compact", "aluminum", "all-day battery"],
      images: ["https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"],
      description: "Compact 13.3-inch stunner with razor-thin bezels, glass precision trackpad, and vibrant Quad HD Retina resolution.",
      specifications: { "Display": '13.3" QHD Retina 500 nits', "Processor": "Intel Core i5-1340P", "RAM": "16GB LPDDR5", "Storage": "512GB SSD", "Battery": "58Wh (14 hrs)" },
    },
    {
      name: "PhantomX Beast 16",
      cat: "Laptops",
      brand: "Phantom",
      price: 112999,
      mrp: 129999,
      rating: 4.6,
      reviewCount: 140,
      stock: 11,
      tags: ["gaming", "liquid cooling", "RGB", "165Hz"],
      images: ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80"],
      description: "Aggressive styling meets serious horsepower with external magnetic liquid cooler support and Dolby Atmos surround audio.",
      specifications: { "Display": '16.0" QHD+ 165Hz 3ms', "Processor": "AMD Ryzen 7 7840HS", "GPU": "RTX 4070 8GB GDDR6", "RAM": "32GB DDR5", "Storage": "1TB SSD" },
    },
    {
      name: "LiteBook Student Edition",
      cat: "Laptops",
      brand: "Pulse",
      price: 29999,
      mrp: 34999,
      rating: 4.1,
      reviewCount: 640,
      stock: 55,
      tags: ["budget", "student", "online classes", "long battery"],
      images: ["https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80"],
      description: "Affordable and reliable student laptop equipped with HD webcam, noise-canceling dual mics, and spill-resistant keyboard.",
      specifications: { "Display": '14.0" HD Anti-glare', "Processor": "Intel Celeron N4500", "RAM": "8GB DDR4", "Storage": "256GB SSD", "OS": "Windows 11 Home" },
    },
    {
      name: "Veloce Developer Pro 16",
      cat: "Laptops",
      brand: "Veloce",
      price: 92999,
      mrp: 104999,
      rating: 4.7,
      reviewCount: 198,
      stock: 15,
      tags: ["developer", "linux ready", "32GB RAM", "high core count"],
      images: ["https://images.unsplash.com/photo-1537498425277-c283d32ef9db?auto=format&fit=crop&w=800&q=80"],
      description: "Built for software engineers with deep key travel, native Linux compatibility, 32GB RAM, and blazing-fast compilation speeds.",
      specifications: { "Display": '16.0" 2.5K 16:10 90Hz', "Processor": "AMD Ryzen 7 7840U 8C/16T", "RAM": "32GB LPDDR5X", "Storage": "1TB NVMe SSD", "Keyboard": "1.5mm Travel Backlit" },
    },
    {
      name: "TerraBook Rugged Field 14",
      cat: "Laptops",
      brand: "Titan",
      price: 89999,
      mrp: 102999,
      rating: 4.5,
      reviewCount: 75,
      stock: 10,
      tags: ["rugged", "outdoor", "water resistant", "drop proof"],
      images: ["https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&w=800&q=80"],
      description: "IP53 rated semi-rugged notebook with shock-absorbing corners, outdoor sunlight-readable 1000 nits display, and dual swappable batteries.",
      specifications: { "Display": '14.0" FHD 1000 nits Glove-Touch', "Processor": "Intel Core i5-1335U", "RAM": "16GB RAM", "Storage": "512GB Encrypted SSD", "Protection": "MIL-STD-810H" },
    },

    /* ============================================================
       2. SMARTPHONES (16 Products)
       ============================================================ */
    {
      name: "Pulse X12 Smartphone",
      cat: "Smartphones",
      brand: "Pulse",
      price: 32999,
      mrp: 37999,
      rating: 4.5,
      reviewCount: 980,
      stock: 60,
      tags: ["5G", "triple camera", "fast charging", "AMOLED"],
      images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80"],
      description: "Pulse X12 features a crystal-clear 108MP triple camera system, vibrant 120Hz AMOLED display, and 67W Turbo Flash Charging.",
      specifications: { "Display": '6.67" FHD+ AMOLED 120Hz', "Processor": "Snapdragon 7+ Gen 2", "Camera": "108MP OIS + 8MP UW + 2MP Macro", "Battery": "5000mAh, 67W Fast Charge" },
    },
    {
      name: "Orion Edge Pro",
      cat: "Smartphones",
      brand: "Orion",
      price: 59999,
      mrp: 66999,
      rating: 4.6,
      reviewCount: 640,
      stock: 24,
      tags: ["flagship", "AMOLED", "telephoto", "wireless charging"],
      images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80"],
      description: "Flagship performance powered by Snapdragon 8 Gen 3, periscope 5x optical zoom camera, and premium ceramic-glass composite finish.",
      specifications: { "Display": '6.78" 1.5K LTPO AMOLED 1-120Hz', "Processor": "Snapdragon 8 Gen 3", "Camera": "50MP 1-inch + 50MP UW + 50MP 5x Tele", "Charging": "100W Wired + 50W Wireless" },
    },
    {
      name: "Vibe Lite 5G",
      cat: "Smartphones",
      brand: "Vibe",
      price: 15999,
      mrp: 18999,
      rating: 4.1,
      reviewCount: 1120,
      stock: 80,
      tags: ["budget", "5G", "monster battery", "expandable"],
      images: ["https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80"],
      description: "Vibe Lite 5G is the ultimate budget champion with dual 5G SIM standby, massive 6000mAh two-day battery, and smooth 90Hz display.",
      specifications: { "Display": '6.58" FHD+ 90Hz', "Processor": "Dimensity 6080 5G", "Camera": "50MP AI Dual Camera", "Battery": "6000mAh, 33W Fast Charge" },
    },
    {
      name: "Nexus One Ultra 5G",
      cat: "Smartphones",
      brand: "Nexus",
      price: 82999,
      mrp: 94999,
      rating: 4.8,
      reviewCount: 420,
      stock: 18,
      tags: ["flagship", "AI camera", "titanium frame", "IP68"],
      images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80"],
      description: "Titanium grade aerospace body packed with AI photo magic tools, satellite connectivity, and industry-leading IP68 water resistance.",
      specifications: { "Display": '6.8" Quad HD+ Dynamic AMOLED 2X', "Processor": "Exynos 2400 / SD 8 Gen 3", "Camera": "200MP + 50MP + 12MP + 10MP", "Build": "Titanium Frame + Gorilla Armor" },
    },
    {
      name: "Lumina Pure Fold 3",
      cat: "Smartphones",
      brand: "Lumina",
      price: 124999,
      mrp: 139999,
      rating: 4.7,
      reviewCount: 185,
      stock: 8,
      tags: ["foldable", "multitasking", "flagship", "dual screen"],
      images: ["https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80"],
      description: "Next-gen zero-gap foldable phone that unfolds into an 8-inch mini workstation for seamless side-by-side multitasking.",
      specifications: { "Main Display": '8.0" Foldable LTPO 120Hz', "Cover Display": '6.4" OLED 120Hz', "Processor": "Snapdragon 8 Gen 3", "RAM/Storage": "16GB / 512GB" },
    },
    {
      name: "Pixelar Prime 128GB",
      cat: "Smartphones",
      brand: "Pixelar",
      price: 44999,
      mrp: 51999,
      rating: 4.6,
      reviewCount: 730,
      stock: 35,
      tags: ["clean android", "night photography", "compact", "wireless charging"],
      images: ["https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=800&q=80"],
      description: "Pure clean software experience with computational photography algorithms that capture astonishing low-light night portraits.",
      specifications: { "Display": '6.3" Actua OLED 120Hz', "Processor": "Custom AI Tensor Core", "Camera": "50MP Dual Pixel + 48MP UW", "Software": "7 Years Guaranteed OS Updates" },
    },
    {
      name: "Horizon Z Pro Max",
      cat: "Smartphones",
      brand: "Horizon",
      price: 69999,
      mrp: 79999,
      rating: 4.7,
      reviewCount: 310,
      stock: 20,
      tags: ["cinematic video", "curved display", "portrait mode", "120W charge"],
      images: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80"],
      description: "Hyper-curved quad borderless screen engineered for cinematic 4K HDR Dolby Vision recording and lightning 120W flash charge.",
      specifications: { "Display": '6.74" Quad-Curved OLED 1.5K', "Processor": "Dimensity 9300+", "Charging": "120W HyperCharge (0-100% in 19 min)", "Audio": "Dual Stereo Dolby Atmos" },
    },
    {
      name: "NovaPulse Compact 5G",
      cat: "Smartphones",
      brand: "Nova",
      price: 27999,
      mrp: 31999,
      rating: 4.4,
      reviewCount: 490,
      stock: 42,
      tags: ["compact", "one hand", "lightweight", "stylish"],
      images: ["https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=800&q=80"],
      description: "Comfortable one-hand form factor weighing just 165 grams with edge-to-edge vibrant OLED and studio selfie portrait lighting.",
      specifications: { "Display": '6.1" Full HD+ OLED 90Hz', "Processor": "Snapdragon 6 Gen 1", "Camera": "64MP Main + 32MP Eye-AF Selfie", "Weight": "165 grams" },
    },
    {
      name: "Stellar 9 Power Edition",
      cat: "Smartphones",
      brand: "Stellar",
      price: 21999,
      mrp: 25999,
      rating: 4.3,
      reviewCount: 880,
      stock: 58,
      tags: ["7000mAh", "battery beast", "5G", "fast gaming"],
      images: ["https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80"],
      description: "Unrivaled battery champion packing a gigantic 7000mAh battery that easily powers through 3 days of non-stop usage.",
      specifications: { "Display": '6.7" Super AMOLED Plus', "Battery": "7000mAh with Reverse Wired Charging", "Processor": "Exynos 1380 5G", "Storage": "8GB RAM + 128GB (up to 1TB microSD)" },
    },
    {
      name: "Titan Shield Rugged Phone",
      cat: "Smartphones",
      brand: "Titan",
      price: 34999,
      mrp: 39999,
      rating: 4.5,
      reviewCount: 160,
      stock: 25,
      tags: ["rugged", "thermal camera", "drop resistant", "outdoor"],
      images: ["https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=800&q=80"],
      description: "Extreme condition rugged smartphone with built-in FLIR thermal imaging, laser rangefinder, and military drop-proof casing.",
      specifications: { "Durability": "IP68 / IP69K / MIL-STD-810H", "Special Sensor": "FLIR Lepton Thermal Imaging", "Battery": "9600mAh Mega Pack", "Display": '6.58" Gorilla Glass Victus' },
    },
    {
      name: "Zenith View 120Hz",
      cat: "Smartphones",
      brand: "Zenith",
      price: 23999,
      mrp: 28999,
      rating: 4.3,
      reviewCount: 510,
      stock: 48,
      tags: ["120Hz", "stereo speakers", "fast response", "budget 5G"],
      images: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80"],
      description: "Buttery smooth 120Hz visual experience with Hi-Res certified stereo audio and Sony IMX sensor for vivid family snapshots.",
      specifications: { "Display": '6.67" IPS FHD+ 120Hz', "Processor": "Snapdragon 695 5G", "Camera": "64MP Sony IMX682", "Battery": "5000mAh, 44W FlashCharge" },
    },
    {
      name: "Echo Play Budget 4G",
      cat: "Smartphones",
      brand: "Pulse",
      price: 8999,
      mrp: 10999,
      rating: 4.0,
      reviewCount: 1450,
      stock: 120,
      tags: ["ultra budget", "entry level", "large screen", "dual sim"],
      images: ["https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=800&q=80"],
      description: "Accessible, reliable entry smartphone with crisp HD+ screen, long battery endurance, and simple intuitive interface.",
      specifications: { "Display": '6.5" HD+ Dot Drop', "Processor": "Octa-Core Helio G36", "Battery": "5000mAh, 10W micro-USB", "Memory": "4GB RAM + 64GB Storage" },
    },
    {
      name: "Aura Infinity Ceramic",
      cat: "Smartphones",
      brand: "Aura",
      price: 74999,
      mrp: 84999,
      rating: 4.8,
      reviewCount: 220,
      stock: 15,
      tags: ["luxury", "ceramic back", "hasselblad camera", "fast charging"],
      images: ["https://images.unsplash.com/photo-1530319067432-f2a729c03db5?auto=format&fit=crop&w=800&q=80"],
      description: "Nano-microcrystalline ceramic chassis with co-engineered color grading by optical masters and ultra-linear haptic feedback.",
      specifications: { "Display": '6.7" 2K 10-bit LTPO OLED', "Processor": "Snapdragon 8 Gen 3", "Camera": "50MP Triple Master Cam", "Build": "Micro-Curved Zirconia Ceramic" },
    },
    {
      name: "Apex Gamer Phone 8 Pro",
      cat: "Smartphones",
      brand: "Apex",
      price: 52999,
      mrp: 59999,
      rating: 4.6,
      reviewCount: 380,
      stock: 22,
      tags: ["gaming", "shoulder triggers", "165Hz AMOLED", "RGB"],
      images: ["https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?auto=format&fit=crop&w=800&q=80"],
      description: "Hardcore mobile gaming phone featuring ultrasonic dual shoulder triggers, internal cooling fan, and 165Hz AMOLED screen.",
      specifications: { "Display": '6.78" AMOLED 165Hz 720Hz Touch Sampling', "Processor": "Snapdragon 8+ Gen 2 OC", "Controls": "Capacitive Air Triggers", "Battery": "6000mAh Dual-Cell 65W" },
    },
    {
      name: "Spectra Zoom Studio",
      cat: "Smartphones",
      brand: "Spectra",
      price: 47999,
      mrp: 54999,
      rating: 4.5,
      reviewCount: 275,
      stock: 30,
      tags: ["portrait master", "optical zoom", "ring light", "vlog"],
      images: ["https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=800&q=80"],
      description: "Equipped with built-in Aura studio ring light and dedicated 3x telephoto portrait lens for breathtaking influencer portraits.",
      specifications: { "Display": '6.78" 1.5K Curved AMOLED', "Camera": "50MP OIS + 50MP 3x Portrait + Aura Light", "Selfie": "50MP Dual AF", "Battery": "5000mAh, 80W FlashCharge" },
    },
    {
      name: "Helios Eco Recycled 5G",
      cat: "Smartphones",
      brand: "Helios",
      price: 29999,
      mrp: 34999,
      rating: 4.4,
      reviewCount: 190,
      stock: 36,
      tags: ["eco friendly", "modular", "repairable", "5G"],
      images: ["https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=800&q=80"],
      description: "Sustainably built using 70% post-consumer recycled materials with user-replaceable battery and zero carbon packaging footprint.",
      specifications: { "Display": '6.46" OLED FHD+ 90Hz', "Processor": "Qualcomm QCM6490", "Repairability": "Modular screw design (Score 10/10)", "Warranty": "5 Year Manufacturer Warranty" },
    },

    /* ============================================================
       3. HEADPHONES (16 Products)
       ============================================================ */
    {
      name: "SonicWave Pro ANC",
      cat: "Headphones",
      brand: "SonicWave",
      price: 8999,
      mrp: 11999,
      rating: 4.6,
      reviewCount: 2100,
      stock: 120,
      tags: ["gaming", "noise cancelling", "bluetooth", "40h battery"],
      images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"],
      description: "Industry standard active noise cancellation with plush memory foam earcups, transparency mode, and up to 40 hours battery.",
      specifications: { "Driver": "40mm Bio-Cellulose", "ANC": "Hybrid Dual Mic Active Cancellation", "Battery": "40h (ANC on) / 60h (ANC off)", "Codec": "LDAC, AAC, SBC" },
    },
    {
      name: "BassCore Studio",
      cat: "Headphones",
      brand: "BassCore",
      price: 4499,
      mrp: 5999,
      rating: 4.3,
      reviewCount: 860,
      stock: 200,
      tags: ["bass", "wired", "studio monitor", "DJ"],
      images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80"],
      description: "Punchy deep sub-bass response tuned for modern hip-hop, EDM, and studio monitoring with 90-degree swiveling earcups.",
      specifications: { "Driver": "50mm Neodymium Magnet", "Frequency": "15Hz - 28,000Hz", "Cable": "Detachable 3m Coiled + 1.2m Straight", "Plug": "3.5mm with 6.35mm gold adapter" },
    },
    {
      name: "AirBuds Mini",
      cat: "Headphones",
      brand: "AirBuds",
      price: 2999,
      mrp: 3999,
      rating: 4.2,
      reviewCount: 1500,
      stock: 300,
      tags: ["earbuds", "compact", "TWS", "touch controls"],
      images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80"],
      description: "Pocket-sized true wireless earbuds with crystal-clear calls, touch controls, and IPX5 splash resistance.",
      specifications: { "Driver": "10mm Dynamic", "Battery Life": "6h earbuds + 24h case", "Water Resistance": "IPX5", "Bluetooth": "v5.3 with Instant Pair" },
    },
    {
      name: "SoundPure Reference 500",
      cat: "Headphones",
      brand: "SoundPure",
      price: 18999,
      mrp: 23999,
      rating: 4.9,
      reviewCount: 310,
      stock: 28,
      tags: ["audiophile", "open back", "hi-res", "planar"],
      images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80"],
      description: "Open-back reference audiophile headphones delivering an expansive soundstage and flat neutral acoustic mastering curve.",
      specifications: { "Type": "Open-Back Acoustic", "Impedance": "80 Ohms", "Frequency Response": "5Hz - 42,000Hz", "Ear cushions": "Breathable Velour Pads" },
    },
    {
      name: "AeroPods Max Spatial",
      cat: "Headphones",
      brand: "Aero",
      price: 24999,
      mrp: 29999,
      rating: 4.8,
      reviewCount: 440,
      stock: 35,
      tags: ["spatial audio", "premium", "aluminum", "head tracking"],
      images: ["https://images.unsplash.com/photo-1545127398-14699f92334b?auto=format&fit=crop&w=800&q=80"],
      description: "Luxury over-ear headphones with dynamic head-tracking spatial audio, anodized aluminum cups, and knit-mesh canopy headband.",
      specifications: { "Acoustic": "Custom 40mm Dynamic Driver", "Microphones": "9 Total Mics for ANC and Calls", "Battery": "25h with Spatial Audio Enabled" },
    },
    {
      name: "BassMonster Wireless Over-Ear",
      cat: "Headphones",
      brand: "BassCore",
      price: 6499,
      mrp: 7999,
      rating: 4.4,
      reviewCount: 920,
      stock: 85,
      tags: ["extra bass", "foldable", "EQ preset", "multipoint"],
      images: ["https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80"],
      description: "Feel the club rhythm with dedicated bass boost slider, seamless 2-device multipoint Bluetooth pairing, and fold-flat travel design.",
      specifications: { "Bass Modes": "3 Levels Electro-Bass Boost", "Battery": "50 Hours Playtime", "Fast Charge": "10 min for 4 hours", "Bluetooth": "v5.2 Multipoint" },
    },
    {
      name: "EchoBuds Pro Noise Cancel",
      cat: "Headphones",
      brand: "SonicWave",
      price: 6999,
      mrp: 8999,
      rating: 4.5,
      reviewCount: 1180,
      stock: 95,
      tags: ["ANC earbuds", "wireless charging", "low latency", "touch"],
      images: ["https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80"],
      description: "Compact in-ear earbuds with 42dB adaptive active noise canceling, Qi wireless charging case, and 45ms gaming low-latency mode.",
      specifications: { "ANC Depth": "Up to -42dB Adaptive", "Wireless Case": "Qi Wireless + USB-C", "Mics": "6 Mics with Wind Noise Reduction", "Latency": "45ms Game Mode" },
    },
    {
      name: "PulseTrack Sport Earhooks",
      cat: "Headphones",
      brand: "Pulse",
      price: 3799,
      mrp: 4999,
      rating: 4.3,
      reviewCount: 650,
      stock: 140,
      tags: ["running", "sport", "earhook", "IPX7 waterproof"],
      images: ["https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80"],
      description: "Secure flexible earhook design that never falls out during intense marathon training, HIIT workouts, or rainy outdoor runs.",
      specifications: { "Waterproof": "IPX7 Sweat & Submersion Resistant", "Battery": "10h on buds + 40h in charging case", "Fit": "Ergonomic Memory Silicone Hooks" },
    },
    {
      name: "StudioMaster Pro Closed-Back",
      cat: "Headphones",
      brand: "SoundPure",
      price: 12999,
      mrp: 15499,
      rating: 4.7,
      reviewCount: 380,
      stock: 40,
      tags: ["recording", "podcast", "passive isolation", "flat response"],
      images: ["https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&w=800&q=80"],
      description: "A staple in broadcast and podcasting studios worldwide, offering supreme passive sound isolation and high dynamic range.",
      specifications: { "Type": "Closed-Back Dynamic", "Frequency": "10Hz - 35,000Hz", "Impedance": "250 Ohms (Requires Amp for max output)", "Weight": "250g without cable" },
    },
    {
      name: "UltraQuiet 45 Bluetooth Headset",
      cat: "Headphones",
      brand: "SonicWave",
      price: 14999,
      mrp: 17999,
      rating: 4.7,
      reviewCount: 520,
      stock: 45,
      tags: ["travel", "airplane", "comfort", "ANC"],
      images: ["https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=800&q=80"],
      description: "Ultra-plush synthetic leather cushions created for long flight comfort with atmospheric pressure optimization and voice clarity.",
      specifications: { "Battery": "30 Hours ANC", "Weight": "238 grams (Ultra Light)", "ANC Chip": "Dual-Core Audio Engine", "Carry Case": "Hard EVA Travel Case Included" },
    },
    {
      name: "RetroVibe Vintage Audio",
      cat: "Headphones",
      brand: "RetroVibe",
      price: 5499,
      mrp: 6999,
      rating: 4.3,
      reviewCount: 410,
      stock: 60,
      tags: ["vintage", "leather", "brass", "warm sound"],
      images: ["https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80"],
      description: "Warm analog acoustic timbre wrapped in real stitched leather and brushed brass hardware reminiscent of 1970s studio classics.",
      specifications: { "Materials": "Handcrafted Leather & Brass", "Driver": "40mm Customized Mylar", "Cable": "Woven Fabric Tangle-Free 3.5mm", "Microphone": "In-line with Call Control" },
    },
    {
      name: "GamerPulse 7.1 RGB Headset",
      cat: "Headphones",
      brand: "Titan",
      price: 4999,
      mrp: 6499,
      rating: 4.5,
      reviewCount: 890,
      stock: 110,
      tags: ["gaming", "surround 7.1", "RGB", "retractable mic"],
      images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80"],
      description: "Pinpoint in-game footsteps with virtual 7.1 surround sound, clear broadcast-quality retractable mic, and customizable RGB lighting.",
      specifications: { "Surround": "Virtual 7.1 Positional Sound", "Mic": "Noise-Canceling Retractable Boom", "Lighting": "16.8M Color RGB Sync", "Compatibility": "PC / PS5 / Xbox / Switch" },
    },
    {
      name: "OpenEar Bone Conduction",
      cat: "Headphones",
      brand: "Pulse",
      price: 7999,
      mrp: 9999,
      rating: 4.4,
      reviewCount: 340,
      stock: 50,
      tags: ["bone conduction", "cycling", "open ear", "safety"],
      images: ["https://images.unsplash.com/photo-1577174881658-0f30ed549adc?auto=format&fit=crop&w=800&q=80"],
      description: "Leave your ears open to hear traffic and surroundings while cycling or jogging, transmitting audio via cheekbone vibrations.",
      specifications: { "Technology": "9th Gen Bone Conduction Transducers", "Battery": "10h Continuous Audio", "Water Resistance": "IP67 Dust & Water Proof", "Weight": "29 grams" },
    },
    {
      name: "NanoPods Pocket Wireless",
      cat: "Headphones",
      brand: "AirBuds",
      price: 1999,
      mrp: 2799,
      rating: 4.1,
      reviewCount: 2200,
      stock: 350,
      tags: ["budget earbuds", "compact", "calls", "fast pair"],
      images: ["https://images.unsplash.com/photo-1590658006821-04f4008d5717?auto=format&fit=crop&w=800&q=80"],
      description: "Super lightweight earbuds with intuitive tap controls, clear voice ENC microphones, and quick Type-C charging.",
      specifications: { "Weight": "3.5g per earbud", "Total Playtime": "20 Hours", "Bluetooth": "v5.3 Low Energy", "Driver": "13mm Dynamic Bass" },
    },
    {
      name: "Audiophile Stage 2 Planar",
      cat: "Headphones",
      brand: "SoundPure",
      price: 34999,
      mrp: 41999,
      rating: 4.9,
      reviewCount: 120,
      stock: 16,
      tags: ["planar magnetic", "audiophile", "ultra high resolution", "wooden"],
      images: ["https://images.unsplash.com/photo-1520170350707-b2da59970118?auto=format&fit=crop&w=800&q=80"],
      description: "Planar magnetic transducers with nanometer-thin diaphragm for microscopic transient detail and ultra-low harmonic distortion.",
      specifications: { "Driver": "100mm Planar Magnetic", "Housing": "Real Solid Walnut Wood", "THD": "< 0.05% @ 1kHz 100dB", "Cables": "Balanced 4.4mm + 6.35mm Single Ended" },
    },
    {
      name: "FlowBeat Neckband Earphones",
      cat: "Headphones",
      brand: "BassCore",
      price: 1499,
      mrp: 2199,
      rating: 4.2,
      reviewCount: 3100,
      stock: 260,
      tags: ["neckband", "magnetic buds", "30h battery", "quick charge"],
      images: ["https://images.unsplash.com/photo-1578319439584-104c94d37305?auto=format&fit=crop&w=800&q=80"],
      description: "Flexible silicone neckband with magnetic snap earbuds, vibration call alerts, and up to 30 hours of continuous music playback.",
      specifications: { "Battery": "30 Hours Playtime (10 min charge = 10 hrs)", "Magnetic": "Auto On/Off with Snap Magnet", "Rating": "IPX4 Water Splash Proof" },
    },

    /* ============================================================
       4. WATCHES (16 Products)
       ============================================================ */
    {
      name: "ChronoFit GT",
      cat: "Watches",
      brand: "Chrono",
      price: 6499,
      mrp: 7999,
      rating: 4.4,
      reviewCount: 530,
      stock: 75,
      tags: ["fitness", "AMOLED", "heart rate", "sleep tracking"],
      images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80"],
      description: "ChronoFit GT features a brilliant always-on AMOLED display, 100+ workout sports modes, continuous SpO2 and stress tracking.",
      specifications: { "Display": '1.43" Always-On AMOLED', "Battery": "Up to 12 Days", "Sensors": "Heart Rate, SpO2, Accelerometer, Sleep", "Water Rating": "5ATM (50 meters)" },
    },
    {
      name: "ClassicTime Steel",
      cat: "Watches",
      brand: "ClassicTime",
      price: 12999,
      mrp: 14999,
      rating: 4.5,
      reviewCount: 210,
      stock: 40,
      tags: ["analog", "formal", "stainless steel", "sapphire glass"],
      images: ["https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80"],
      description: "Timeless elegance with a 316L surgical-grade stainless steel bracelet, scratch-resistant sapphire crystal glass, and date display.",
      specifications: { "Case Size": "42mm", "Material": "316L Stainless Steel", "Glass": "Anti-Reflective Sapphire Crystal", "Movement": "Japanese Miyota Quartz" },
    },
    {
      name: "Horizon SmartBand 6",
      cat: "Watches",
      brand: "Horizon",
      price: 2499,
      mrp: 3499,
      rating: 4.2,
      reviewCount: 1850,
      stock: 220,
      tags: ["fitness band", "slim", "step tracker", "waterproof"],
      images: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80"],
      description: "Featherweight fitness band with curved color screen, 14-day battery life, and automatic workout detection for daily health goals.",
      specifications: { "Display": '1.47" Full Touch Color Screen', "Battery": "14 Days Typical Usage", "Tracking": "Steps, Calories, Sleep, 24/7 Heart Rate", "Water Resistance": "50m Water Resistant" },
    },
    {
      name: "Apex Titanium Diver 300m",
      cat: "Watches",
      brand: "Apex",
      price: 28999,
      mrp: 34999,
      rating: 4.8,
      reviewCount: 95,
      stock: 18,
      tags: ["automatic", "diver", "titanium", "300m water resistant"],
      images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80"],
      description: "Professional grade diver watch with Grade 2 titanium case, unidirectional ceramic bezel, helium escape valve, and Super-LumiNova markers.",
      specifications: { "Movement": "Automatic NH35 (41h power reserve)", "Water Resistance": "300m / 30 ATM", "Bezel": "120-Click Ceramic", "Case": "43mm Solid Titanium" },
    },
    {
      name: "Zenith Chronograph Leather",
      cat: "Watches",
      brand: "Zenith",
      price: 16499,
      mrp: 19999,
      rating: 4.6,
      reviewCount: 140,
      stock: 30,
      tags: ["chronograph", "genuine leather", "stopwatch", "classic"],
      images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80"],
      description: "Sophisticated triple sub-dial chronograph with Italian full-grain leather strap and vintage sunburst dial finish.",
      specifications: { "Sub-dials": "60-second, 30-minute, 24-hour", "Strap": "22mm Genuine Italian Calf Leather", "Glass": "Hardened Mineral Crystal", "Water Resistance": "50m" },
    },
    {
      name: "PulseWatch Ultra AMOLED",
      cat: "Watches",
      brand: "Pulse",
      price: 8999,
      mrp: 11499,
      rating: 4.6,
      reviewCount: 620,
      stock: 65,
      tags: ["bluetooth calling", "GPS", "AMOLED", "smartwatch"],
      images: ["https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=800&q=80"],
      description: "Crystal-clear HD Bluetooth speaker calling straight from your wrist, standalone multi-system GPS routing, and 1000 nits peak brightness.",
      specifications: { "Display": '1.96" HD AMOLED 410x502', "Connectivity": "Bluetooth Calling with Mic + Speaker", "GPS": "Built-in GPS/GLONASS/Galileo", "Battery": "7 Days Heavy Use" },
    },
    {
      name: "Royale Automatic Skeleton",
      cat: "Watches",
      brand: "ClassicTime",
      price: 21999,
      mrp: 26999,
      rating: 4.7,
      reviewCount: 115,
      stock: 22,
      tags: ["skeleton", "automatic", "luxury", "mechanical"],
      images: ["https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=800&q=80"],
      description: "Mesmerizing open-heart skeleton dial showing the mechanical balance wheel pulsing with every second, requiring no battery.",
      specifications: { "Movement": "Self-Winding 24-Jewel Automatic", "Power Reserve": "42 Hours", "Back": "Exhibition Mineral Glass Caseback", "Strap": "Butterfly Deployant Clasp" },
    },
    {
      name: "SolarDrive Rugged GPS",
      cat: "Watches",
      brand: "Chrono",
      price: 17999,
      mrp: 21999,
      rating: 4.7,
      reviewCount: 175,
      stock: 35,
      tags: ["solar powered", "rugged", "altimeter", "outdoor GPS"],
      images: ["https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=800&q=80"],
      description: "Infinite battery potential with integrated solar charging lens, ABC sensors (Altimeter, Barometer, Compass), and topo maps.",
      specifications: { "Charging": "Solar Powered + USB Clip", "Sensors": "Barometric Altimeter, 3-Axis Compass, Thermometer", "Shock Resistance": "ISO 1413 Shock Proof" },
    },
    {
      name: "Minimalist Rose Gold Mesh",
      cat: "Watches",
      brand: "Aura",
      price: 7499,
      mrp: 9499,
      rating: 4.4,
      reviewCount: 380,
      stock: 55,
      tags: ["minimalist", "rose gold", "mesh band", "women"],
      images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80"],
      description: "Sleek ultra-thin 6mm profile with shimmering rose gold ion plating and flexible Milanese stainless steel magnetic mesh band.",
      specifications: { "Case Thickness": "6.2mm Ultra Thin", "Case Diameter": "36mm", "Plating": "PVD Rose Gold 5-Micron", "Band": "Adjustable Milanese Mesh" },
    },
    {
      name: "Velocity Sport Chrono",
      cat: "Watches",
      brand: "Apex",
      price: 11499,
      mrp: 13999,
      rating: 4.5,
      reviewCount: 290,
      stock: 45,
      tags: ["tachymeter", "motorsport", "silicone strap", "chrono"],
      images: ["https://images.unsplash.com/photo-1539874701005-525f50a2757c?auto=format&fit=crop&w=800&q=80"],
      description: "Motorsport-inspired speed chronograph featuring a tachymeter scale bezel for calculating velocity and sweat-proof tire-tread silicone band.",
      specifications: { "Bezel": "Tachymeter Scale", "Strap": "Vented Fluororubber Silicone", "Waterproof": "100m / 10 ATM", "Dial": "Carbon Fiber Texture Pattern" },
    },
    {
      name: "AeroFit Active 2 Tracker",
      cat: "Watches",
      brand: "Aero",
      price: 4999,
      mrp: 6299,
      rating: 4.3,
      reviewCount: 710,
      stock: 90,
      tags: ["smartwatch", "music control", "aluminum", "100+ sports"],
      images: ["https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=800&q=80"],
      description: "Lightweight aircraft aluminum bezel with customizable watch faces, women health tracking, and remote camera/music shutter.",
      specifications: { "Display": '1.78" High-Res TFT LCD', "Weight": "38g with strap", "Battery": "8-10 Days", "Compatibility": "Android and iOS via App" },
    },
    {
      name: "Heritage Roman Dial Luxury",
      cat: "Watches",
      brand: "ClassicTime",
      price: 19499,
      mrp: 23999,
      rating: 4.7,
      reviewCount: 130,
      stock: 25,
      tags: ["roman numerals", "blue hands", "guilloche dial", "formal"],
      images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80"],
      description: "Traditional dress watch featuring deep blue thermal treated hands, guilloche embossed silver dial, and classic Roman numeral hour markers.",
      specifications: { "Dial": "Engraved Guilloche Pattern with Blued Hands", "Movement": "Swiss Ronda Quartz", "Case": "40mm Polished Stainless Steel", "Strap": "Alligator Embossed Leather" },
    },
    {
      name: "Stealth Tactical Military 50mm",
      cat: "Watches",
      brand: "Titan",
      price: 5999,
      mrp: 7499,
      rating: 4.4,
      reviewCount: 840,
      stock: 80,
      tags: ["tactical", "shockproof", "dual time", "military"],
      images: ["https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&w=800&q=80"],
      description: "Heavy-duty resin armor with world time for 48 cities, 1/1000th second countdown stopwatch, and high-intensity EL backlight.",
      specifications: { "Case Diameter": "51mm Rugged Resin", "Water Resistance": "200m / 20 BAR", "Functions": "5 Daily Alarms, World Time, Timer, Hourly Chime" },
    },
    {
      name: "Luna Elegant Ceramic Watch",
      cat: "Watches",
      brand: "Aura",
      price: 15999,
      mrp: 18999,
      rating: 4.6,
      reviewCount: 160,
      stock: 30,
      tags: ["ceramic", "diamond markers", "scratchproof", "women"],
      images: ["https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&w=800&q=80"],
      description: "Gleaming high-tech white ceramic link bracelet with diamond-cut hour indices and butterfly hidden push clasp that never fades.",
      specifications: { "Material": "High-Gloss High-Tech Ceramic", "Glass": "Curved Sapphire Crystal", "Indices": "Swarovski Crystal Markers", "Water Rating": "30m" },
    },
    {
      name: "PulsePro Runner ECG GPS",
      cat: "Watches",
      brand: "Pulse",
      price: 13999,
      mrp: 16999,
      rating: 4.7,
      reviewCount: 320,
      stock: 40,
      tags: ["ECG", "blood pressure", "dual frequency GPS", "triathlon"],
      images: ["https://images.unsplash.com/photo-1509741102003-ca64bfe5f069?auto=format&fit=crop&w=800&q=80"],
      description: "Medical-grade optical ECG sensor, dual-band L1+L5 GPS track precision, and advanced VO2 Max recovery metrics for marathoners.",
      specifications: { "ECG": "Medical-Grade Electrocardiogram Analysis", "GPS": "Dual-Band L1+L5 Sub-meter Precision", "Display": '1.4" AMOLED 454x454', "Battery": "14 Days Sport Mode" },
    },
    {
      name: "Vintage Field Mechanical",
      cat: "Watches",
      brand: "RetroVibe",
      price: 9999,
      mrp: 12499,
      rating: 4.5,
      reviewCount: 215,
      stock: 38,
      tags: ["field watch", "hand wind", "NATO strap", "lume"],
      images: ["https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=800&q=80"],
      description: "Authentic military field heritage with matte blasted case, 24-hour inner tactical chapter ring, and heavy-duty nylon NATO strap.",
      specifications: { "Movement": "Manual Hand-Wind Mechanical", "Case": "38mm Bead-Blasted Steel", "Lume": "C3 Super-LumiNova Green Glow", "Strap": "Military Olive Nylon NATO" },
    },

    /* ============================================================
       5. SHOES (16 Products)
       ============================================================ */
    {
      name: "StrideMax Runner",
      cat: "Shoes",
      brand: "Stride",
      price: 3999,
      mrp: 4999,
      rating: 4.3,
      reviewCount: 690,
      stock: 150,
      tags: ["running", "lightweight", "breathable", "cushion"],
      images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80"],
      description: "StrideMax Runner is engineered with responsive foam cushioning and breathable engineered mesh for smooth road runs.",
      specifications: { "Sole": "High-Rebound EVA Midsole", "Upper": "Engineered Knit Mesh", "Closure": "Lace-Up", "Weight": "240 grams (Size UK 8)" },
    },
    {
      name: "UrbanStep Casual",
      cat: "Shoes",
      brand: "Urban",
      price: 2499,
      mrp: 3299,
      rating: 4.1,
      reviewCount: 410,
      stock: 180,
      tags: ["casual", "daily", "sneaker", "comfortable"],
      images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80"],
      description: "UrbanStep Casual pairs minimal street aesthetic with memory foam footbeds for effortless all-day college and workplace style.",
      specifications: { "Sole": "Vulcanized Non-Slip Rubber", "Upper": "Canvas and Vegan Suede", "Insole": "High-Density Memory Foam Cushion" },
    },
    {
      name: "CloudBurst Cushion Running",
      cat: "Shoes",
      brand: "Stride",
      price: 6499,
      mrp: 7999,
      rating: 4.7,
      reviewCount: 540,
      stock: 70,
      tags: ["marathon", "nitrogen foam", "high arch", "energy return"],
      images: ["https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80"],
      description: "Nitrogen-infused super-critical foam provides 85% energy return on every strike, protecting knees on long distance runs.",
      specifications: { "Midsole": "Supercritical Nitrogen Foam", "Outsole": "Continental Rubber Grip", "Drop": "8mm Heel-to-Toe", "Type": "Neutral Road Running" },
    },
    {
      name: "AeroWalk Air Sneakers",
      cat: "Shoes",
      brand: "Aero",
      price: 3499,
      mrp: 4499,
      rating: 4.4,
      reviewCount: 820,
      stock: 110,
      tags: ["air cushion", "walking", "gym", "trendy"],
      images: ["https://images.unsplash.com/photo-1551107696-a4b085a6d9a6?auto=format&fit=crop&w=800&q=80"],
      description: "Visible air pocket heel cushion absorbs shock instantly while walking 10,000+ steps around town or hitting the treadmill.",
      specifications: { "Heel Tech": "360-Degree Air Chamber Sole", "Lining": "Sweat-Wicking Textile", "Arch Support": "Orthotic Molded Cup" },
    },
    {
      name: "TrailForge All-Terrain Hiking",
      cat: "Shoes",
      brand: "Apex",
      price: 5999,
      mrp: 7299,
      rating: 4.6,
      reviewCount: 310,
      stock: 65,
      tags: ["hiking", "waterproof", "vibram sole", "outdoor"],
      images: ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80"],
      description: "Rugged waterproof trail shoes equipped with 5mm multidirectional traction lugs, reinforced rubber toe cap, and rock plate.",
      specifications: { "Outsole": "5mm Deep Lug Deep Grip Rubber", "Membrane": "Waterproof HydroShield", "Toe Bumper": "Reinforced TPU Shield" },
    },
    {
      name: "StreetStar Classic High-Tops",
      cat: "Shoes",
      brand: "Urban",
      price: 2999,
      mrp: 3799,
      rating: 4.3,
      reviewCount: 950,
      stock: 140,
      tags: ["high top", "retro", "streetwear", "canvas"],
      images: ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80"],
      description: "Iconic retro high-top silhouette with ankle support padding, vulcanized waffle rubber sole, and durable 12oz cotton canvas.",
      specifications: { "Upper": "Heavy 12oz Cotton Canvas", "Collar": "Padded Ankle Support", "Sole": "Diamond Pattern Gum Rubber" },
    },
    {
      name: "VelvetWalk Oxford Dress Shoes",
      cat: "Shoes",
      brand: "ClassicTime",
      price: 5499,
      mrp: 6999,
      rating: 4.6,
      reviewCount: 230,
      stock: 45,
      tags: ["formal", "oxford", "genuine leather", "wedding"],
      images: ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80"],
      description: "Handcrafted cap-toe Oxford dress shoe made with burnished Argentine leather and Goodyear-welted construction for boardrooms.",
      specifications: { "Leather": "Full Grain Argentine Calfskin", "Construction": "Goodyear Welted (Resolable)", "Sole": "Leather with Inset Rubber Grip" },
    },
    {
      name: "Velocity Knit Sprint Spikes",
      cat: "Shoes",
      brand: "Stride",
      price: 4799,
      mrp: 5999,
      rating: 4.5,
      reviewCount: 180,
      stock: 50,
      tags: ["track and field", "spikes", "speed", "carbon plate"],
      images: ["https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80"],
      description: "Track sprint shoes with embedded 3/4 carbon propulsion plate and 6 removable pyramid steel spikes for peak acceleration.",
      specifications: { "Plate": "Rigid Carbon Fiber Propulsion Shank", "Spikes": "6-Pin Replaceable Alloy Pins", "Weight": "165 grams ultra-light" },
    },
    {
      name: "TerraGrip Waterproof Boots",
      cat: "Shoes",
      brand: "Apex",
      price: 7499,
      mrp: 8999,
      rating: 4.7,
      reviewCount: 290,
      stock: 40,
      tags: ["boots", "leather", "winter", "waterproof"],
      images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80"],
      description: "Waterproof nubuck leather 6-inch work and mountain boot with rustproof speed hooks and anti-fatigue polyurethane midsole.",
      specifications: { "Upper": "Waterproof Oiled Nubuck", "Insulation": "200g Thermal Lining", "Shaft Height": "6.5 inches Ankle Guard" },
    },
    {
      name: "BreezeStep Slip-on Loafers",
      cat: "Shoes",
      brand: "Urban",
      price: 1999,
      mrp: 2699,
      rating: 4.2,
      reviewCount: 780,
      stock: 160,
      tags: ["slip on", "lightweight", "washable", "summer"],
      images: ["https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80"],
      description: "Featherlight slip-on loafers with elastic side gores and breathable perforated mesh for quick airport security and casual lounging.",
      specifications: { "Closure": "Dual Elastic Gore Slip-On", "Weight": "180g", "Care": "Machine Washable Cold Cycle" },
    },
    {
      name: "MetroGlide Retro Skate",
      cat: "Shoes",
      brand: "Urban",
      price: 3199,
      mrp: 3999,
      rating: 4.4,
      reviewCount: 460,
      stock: 95,
      tags: ["skateboarding", "durable", "suede", "board feel"],
      images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80"],
      description: "Reinforced ollie abrasion patches with dual-density impact foam cupsole designed specifically for street skateboarders.",
      specifications: { "Reinforcement": "DuraCap Rubber Underlays", "Insole": "PopCush Impact Dampening", "Upper": "Heavy Suede & Canvas" },
    },
    {
      name: "UltraFlex Gym Trainer",
      cat: "Shoes",
      brand: "Stride",
      price: 3699,
      mrp: 4699,
      rating: 4.5,
      reviewCount: 620,
      stock: 120,
      tags: ["crossfit", "flat sole", "weightlifting", "stability"],
      images: ["https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80"],
      description: "Wide flat anatomical toe box with rigid heel cup to ensure maximum ground contact stability during squats and deadlifts.",
      specifications: { "Heel Drop": "Zero Drop 0mm", "Toe Box": "Wide Ergonomic Splay", "Side Wrap": "Rubber Rope Grip Side Walls" },
    },
    {
      name: "AlpinePeak Trekking Boot",
      cat: "Shoes",
      brand: "Apex",
      price: 8499,
      mrp: 9999,
      rating: 4.8,
      reviewCount: 170,
      stock: 32,
      tags: ["mountaineering", "gore-tex", "crampon compatible", "heavy duty"],
      images: ["https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?auto=format&fit=crop&w=800&q=80"],
      description: "High altitude trekking boots with GORE-TEX waterproof breathable membrane, ankle flex lock, and semi-automatic crampon heel welt.",
      specifications: { "Membrane": "GORE-TEX Performance Comfort", "Sole": "Vibram Curcuma Mountain Outsole", "Randing": "Full 360° Rubber Rand Protection" },
    },
    {
      name: "Nomad Canvas Daily Sneaker",
      cat: "Shoes",
      brand: "Urban",
      price: 1799,
      mrp: 2399,
      rating: 4.1,
      reviewCount: 1100,
      stock: 200,
      tags: ["everyday", "canvas", "minimalist", "low top"],
      images: ["https://images.unsplash.com/photo-1562183241-b937e95585b6?auto=format&fit=crop&w=800&q=80"],
      description: "Clean minimalist low-top silhouette that pairs effortlessly with jeans, chinos, or shorts in any season.",
      specifications: { "Upper": "100% Organic Cotton Canvas", "Eyelets": "Rust-Free Nickel Grommets", "Insole": "Cushioned EVA" },
    },
    {
      name: "PulseSprint Marathon Racing",
      cat: "Shoes",
      brand: "Pulse",
      price: 9499,
      mrp: 11999,
      rating: 4.8,
      reviewCount: 260,
      stock: 28,
      tags: ["carbon fiber plate", "sub 3 marathon", "peba foam", "racing"],
      images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80"],
      description: "Elite marathon racing shoe combining 100% full curved carbon fiber plate with 40mm stack height PEBA foam.",
      specifications: { "Weight": "190 grams", "Stack Height": "40mm / 32mm (8mm drop)", "Plate": "Full-Length Spoon-Shaped Carbon Fiber", "Upper": "Mono-Mesh AtomKnit" },
    },
    {
      name: "Classic Derby Formal Leather",
      cat: "Shoes",
      brand: "ClassicTime",
      price: 4999,
      mrp: 6299,
      rating: 4.5,
      reviewCount: 340,
      stock: 55,
      tags: ["derby", "formal", "office", "leather lining"],
      images: ["https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=800&q=80"],
      description: "Open lacing Derby shoes crafted from polished black full-grain leather with cushioned leather insole for office comfort.",
      specifications: { "Leather": "Full Grain Smooth Cowhide", "Lining": "Breathable Milled Leather", "Sole": "TPR Durable Non-Slip Base" },
    },

    /* ============================================================
       6. CAMERAS (16 Products)
       ============================================================ */
    {
      name: "LensCraft Z6 Mirrorless",
      cat: "Cameras",
      brand: "LensCraft",
      price: 84999,
      mrp: 94999,
      rating: 4.7,
      reviewCount: 96,
      stock: 12,
      tags: ["mirrorless", "4K", "full frame", "IBIS"],
      images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80"],
      description: "LensCraft Z6 Mirrorless camera features a 24.5MP BSI full-frame sensor, 5-axis sensor-shift image stabilization, and 4K UHD video.",
      specifications: { "Sensor": "24.5MP Full-Frame BSI CMOS", "Video": "4K UHD 60p 10-bit N-Log", "Stabilization": "5-Axis In-Body Sensor Shift (5 stops)", "Mount": "Z-Bayonet Mount" },
    },
    {
      name: "SnapShot Compact",
      cat: "Cameras",
      brand: "SnapShot",
      price: 18999,
      mrp: 22999,
      rating: 4.2,
      reviewCount: 180,
      stock: 35,
      tags: ["compact", "travel", "zoom", "wifi"],
      images: ["https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80"],
      description: "SnapShot Compact fits easily in your jacket pocket with 20x optical zoom lens, optical image stabilization, and instant smartphone transfer.",
      specifications: { "Sensor": '20.1MP 1/2.3" CMOS', "Zoom": "20x Optical / 40x Digital Zoom", "Screen": '3.0" Tilt LCD', "Connectivity": "Wi-Fi & Bluetooth" },
    },
    {
      name: "AlphaView 4K Cinema Camera",
      cat: "Cameras",
      brand: "LensCraft",
      price: 139999,
      mrp: 159999,
      rating: 4.9,
      reviewCount: 75,
      stock: 8,
      tags: ["cinema", "4K 120fps", "dual base ISO", "pro video"],
      images: ["https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=800&q=80"],
      description: "Full-frame cinema line camera with 4K 120p high-frame-rate recording, Dual Base ISO 800/12800, and 15+ stops of dynamic range.",
      specifications: { "Sensor": "12.1MP Full-Frame Exmor R CMOS", "Video": "4K 120p / FHD 240p 10-Bit 4:2:2 All-Intra", "ISO": "80-102,400 (Expandable to 409,600)", "Cooling": "Active Internal Fan (Unlimited Rec)" },
    },
    {
      name: "Lumix Pro Full-Frame 45MP",
      cat: "Cameras",
      brand: "LensCraft",
      price: 114999,
      mrp: 129999,
      rating: 4.8,
      reviewCount: 110,
      stock: 10,
      tags: ["45MP", "commercial photography", "high resolution", "8K"],
      images: ["https://images.unsplash.com/photo-1500634245200-e5245c7574ef?auto=format&fit=crop&w=800&q=80"],
      description: "Ultra-high resolution 45.7MP studio monster with 8K 30p internal RAW video, blackout-free electronic shutter, and deep learning AF.",
      specifications: { "Sensor": "45.7MP Stacked CMOS", "Video": "8K 30p / 4K 120p ProRes RAW", "AF Points": "493-Point Phase Detect with Eye-AF", "Slots": "Dual CFexpress Type B" },
    },
    {
      name: "RetroFilm 35mm Rangefinder",
      cat: "Cameras",
      brand: "RetroVibe",
      price: 49999,
      mrp: 57999,
      rating: 4.6,
      reviewCount: 140,
      stock: 15,
      tags: ["rangefinder", "manual focus", "analog aesthetic", "street photo"],
      images: ["https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=800&q=80"],
      description: "Classic brass rangefinder body with coupled optical split-image viewfinder, manual exposure dials, and film simulation color profiles.",
      specifications: { "Sensor": "26.1MP APS-C X-Trans CMOS", "Viewfinder": "Hybrid Optical / Electronic 3.69M Dot", "Lens": "Fixed 23mm F2.0 Pancake", "Weight": "500g All Metal" },
    },
    {
      name: "ActionCam Extreme 5K 60FPS",
      cat: "Cameras",
      brand: "Apex",
      price: 28999,
      mrp: 34999,
      rating: 4.6,
      reviewCount: 820,
      stock: 55,
      tags: ["action camera", "waterproof", "5K video", "hypersmooth"],
      images: ["https://images.unsplash.com/photo-1564466809058-bf4114d55352?auto=format&fit=crop&w=800&q=80"],
      description: "Rugged waterproof action camera featuring revolutionary 360-degree horizon leveling stabilization and dual front/rear touchscreens.",
      specifications: { "Video": "5.3K 60fps / 4K 120fps / 2.7K 240fps", "Waterproof": "10m without external housing", "Stabilization": "Gyro Horizon-Lock Electronic", "Displays": "Front 1.4\" + Rear 2.27\" Touch" },
    },
    {
      name: "VloggerPod 4K Flip Screen",
      cat: "Cameras",
      brand: "SnapShot",
      price: 36999,
      mrp: 42999,
      rating: 4.5,
      reviewCount: 460,
      stock: 40,
      tags: ["vlogging", "flip screen", "autofocus", "product showcase"],
      images: ["https://images.unsplash.com/photo-1589872782733-4f91e3e7f4c5?auto=format&fit=crop&w=800&q=80"],
      description: "Designed for content creators with 180-degree selfie flip screen, directional 3-capsule mic with windscreen, and product showcase focus mode.",
      specifications: { "Sensor": '20.1MP 1.0" Stacked Sensor', "Lens": "20-70mm F2.0-4.0 Equivalent", "Mic": "3-Capsule Internal Directional with Deadcat", "Weight": "294g" },
    },
    {
      name: "StudioFocus Medium Format 100MP",
      cat: "Cameras",
      brand: "LensCraft",
      price: 289999,
      mrp: 329999,
      rating: 4.9,
      reviewCount: 38,
      stock: 4,
      tags: ["medium format", "100MP", "fashion", "studio"],
      images: ["https://images.unsplash.com/photo-1581591524425-c7e0978865fc?auto=format&fit=crop&w=800&q=80"],
      description: "Unrivaled medium format sensor 1.7x larger than full frame, resolving breathtaking 102MP files with 16-bit RAW color depth.",
      specifications: { "Sensor": "102MP 43.8 x 32.9mm BSI CMOS", "Color Depth": "16-Bit RAW", "IBIS": "5-Axis In-Body Stabilization 6.0 Stops", "Shutter": "Focal Plane + Leaf Shutter Support" },
    },
    {
      name: "InstantPic Vintage Instant Camera",
      cat: "Cameras",
      brand: "SnapShot",
      price: 6499,
      mrp: 7999,
      rating: 4.3,
      reviewCount: 1400,
      stock: 120,
      tags: ["instant photo", "party", "polaroid", "credit card print"],
      images: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80"],
      description: "Print real physical photos instantly in 90 seconds with automatic flash exposure control, selfie mirror, and close-up macro lens.",
      specifications: { "Film": "Instant Film Mini (54 x 86 mm)", "Lens": "2 Components, 2 Elements, f = 60 mm", "Power": "2x AA Batteries (100 prints per charge)" },
    },
    {
      name: "DroneEye 4K Quadcopter Gimbal",
      cat: "Cameras",
      brand: "Apex",
      price: 54999,
      mrp: 64999,
      rating: 4.7,
      reviewCount: 350,
      stock: 25,
      tags: ["drone", "aerial 4K", "3-axis gimbal", "obstacle avoidance"],
      images: ["https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80"],
      description: "Foldable aerial drone under 249 grams with 4K HDR 3-axis mechanical gimbal, 38-minute flight time, and 10km video transmission.",
      specifications: { "Weight": "249g (No registration required in many regions)", "Flight Time": "38 Minutes Max", "Range": "10km 1080p Live Feed", "Sensor": '1/1.3" CMOS 48MP' },
    },
    {
      name: "WildlifePro 600mm DSLR Kit",
      cat: "Cameras",
      brand: "Titan",
      price: 94999,
      mrp: 109999,
      rating: 4.7,
      reviewCount: 120,
      stock: 14,
      tags: ["wildlife", "telephoto", "optical viewfinder", "fast burst"],
      images: ["https://images.unsplash.com/photo-1617005082133-548c4dd27f35?auto=format&fit=crop&w=800&q=80"],
      description: "Weather-sealed high burst DSLR kit bundled with 150-600mm super telephoto zoom lens and optical glass prism viewfinder.",
      specifications: { "Sensor": "32.5MP APS-C Sensor", "Burst Rate": "14 fps Mechanical with Full Tracking", "Weather Sealing": "Magnesium Alloy Splash-Resistant Body" },
    },
    {
      name: "StreetShooter 28mm Prime Compact",
      cat: "Cameras",
      brand: "SnapShot",
      price: 62999,
      mrp: 69999,
      rating: 4.6,
      reviewCount: 195,
      stock: 20,
      tags: ["street photo", "APS-C", "28mm prime", "snap focus"],
      images: ["https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=800&q=80"],
      description: "Purist street photography camera with ultra-sharp 28mm F2.8 lens, high-contrast black & white mode, and snap zone focus.",
      specifications: { "Sensor": "24.2MP APS-C with No Anti-Aliasing Filter", "Lens": "18.3mm F2.8 (28mm Full Frame Equivalent)", "Stabilization": "3-Axis Shake Reduction", "Weight": "257g" },
    },
    {
      name: "AstroMaster Night Sky Camera",
      cat: "Cameras",
      brand: "LensCraft",
      price: 99999,
      mrp: 114999,
      rating: 4.8,
      reviewCount: 88,
      stock: 11,
      tags: ["astrophotography", "hydrogen alpha", "night sky", "low noise"],
      images: ["https://images.unsplash.com/photo-1507646227500-4d389b0012be?auto=format&fit=crop&w=800&q=80"],
      description: "Modified optical low-pass IR filter providing 4x higher transmission of H-alpha light (656nm) to capture deep space red nebulae.",
      specifications: { "Sensor": "30.3MP Full Frame H-Alpha Modified", "Special Mode": "30x Magnification Focus Assist", "Noise": "Extended Long-Exposure Thermal Reduction" },
    },
    {
      name: "MacroVision 90mm Sensor",
      cat: "Cameras",
      brand: "LensCraft",
      price: 78999,
      mrp: 89999,
      rating: 4.6,
      reviewCount: 105,
      stock: 16,
      tags: ["macro", "focus stacking", "1:1 magnification", "ring flash"],
      images: ["https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80"],
      description: "True 1:1 reproduction ratio macro specialist featuring automated in-camera focus bracketing and built-in twin LED guide lights.",
      specifications: { "Magnification": "1:1 Life Size Reproduction", "Focus": "In-Camera Focus Stacking up to 999 Frames", "Minimum Focus Distance": "19cm from sensor" },
    },
    {
      name: "360Sphere VR Dual-Lens",
      cat: "Cameras",
      brand: "Apex",
      price: 39999,
      mrp: 46999,
      rating: 4.5,
      reviewCount: 280,
      stock: 30,
      tags: ["360 camera", "VR", "invisible selfie stick", "5.7K"],
      images: ["https://images.unsplash.com/photo-1519638831568-d9897f54ed69?auto=format&fit=crop&w=800&q=80"],
      description: "Dual 180-degree fisheye lenses capture immersive 5.7K 360-degree footage with automated invisible selfie stick reframing in post.",
      specifications: { "Resolution": "5.7K 30fps 360 Video / 72MP 360 Photos", "Audio": "4-Mic Spatial Ambisonic Surround", "Waterproof": "10m IPX8" },
    },
    {
      name: "CineMaster 8K Production Rig",
      cat: "Cameras",
      brand: "LensCraft",
      price: 349999,
      mrp: 399999,
      rating: 4.9,
      reviewCount: 22,
      stock: 3,
      tags: ["production", "8K RAW", "RED PL mount", "broadcasting"],
      images: ["https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=800&q=80"],
      description: "Hollywood level 8K Super 35mm global shutter cinema sensor with integrated 12G-SDI output, timecode sync, and dual V-mount plate.",
      specifications: { "Sensor": "35.4MP Super 35 Global Shutter", "RAW": "16-bit 8K RAW up to 60fps", "Dynamic Range": "16.5 Stops", "Mount": "Interchangeable PL / EF Mount" },
    },

    /* ============================================================
       7. BACKPACKS (16 Products)
       ============================================================ */
    {
      name: "TrailPack 40L",
      cat: "Backpacks",
      brand: "Trail",
      price: 2999,
      mrp: 3799,
      rating: 4.5,
      reviewCount: 340,
      stock: 90,
      tags: ["travel", "durable", "hiking", "rain cover"],
      images: ["https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80"],
      description: "TrailPack 40L is an all-weather hiking and backpacking bag with padded hip belt, trekking pole loops, and integrated high-visibility rain cover.",
      specifications: { "Capacity": "40 Litres", "Material": "600D Ripstop Polyester", "Weight": "890 grams", "Rain Cover": "Included in bottom zip pocket" },
    },
    {
      name: "CityCarry Laptop Bag",
      cat: "Backpacks",
      brand: "CityCarry",
      price: 1799,
      mrp: 2299,
      rating: 4.3,
      reviewCount: 520,
      stock: 110,
      tags: ["laptop", "commute", "water resistant", "office"],
      images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80"],
      description: "CityCarry Laptop Bag features a plush fleece-lined 15.6-inch laptop compartment, hidden passport pocket, and luggage pass-through strap.",
      specifications: { "Laptop Fit": 'Up to 15.6" Laptop + 11" Tablet', "Capacity": "22 Litres", "Luggage Strap": "Yes, Rear Trolley Sleeve", "Zippers": "YKK Smooth Gliders" },
    },
    {
      name: "PeakNomad Expandable Travel 35L",
      cat: "Backpacks",
      brand: "PeakGear",
      price: 4499,
      mrp: 5499,
      rating: 4.7,
      reviewCount: 410,
      stock: 60,
      tags: ["carry on", "expandable", "clamshell", "TSA friendly"],
      images: ["https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=crop&w=800&q=80"],
      description: "Flight-approved carry-on backpack that opens like a suitcase with compression straps, shoe compartment, and TSA lockable zippers.",
      specifications: { "Dimensions": "50 x 34 x 20 cm (Expands to 25 cm)", "Capacity": "28L - 35L Expanded", "Laptop Sleeve": '17" Padded Shock-Absorbing', "Material": "Water-Repellent 900D Oxford" },
    },
    {
      name: "UrbanCommute Anti-Theft Backpack",
      cat: "Backpacks",
      brand: "CityCarry",
      price: 2499,
      mrp: 3199,
      rating: 4.4,
      reviewCount: 680,
      stock: 95,
      tags: ["anti theft", "hidden zipper", "USB port", "slash proof"],
      images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80"],
      description: "Rear-facing hidden zipper closure stops pickpockets in crowded metro stations, featuring cut-resistant internal layer and USB pass-through.",
      specifications: { "Anti-Theft": "Hidden Zippers + Cut-Proof PP Board", "Charging": "External USB Port with Internal Cable", "Capacity": "20 Litres" },
    },
    {
      name: "AlpineSummit 65L Expedition Rucksack",
      cat: "Backpacks",
      brand: "Trail",
      price: 5999,
      mrp: 7499,
      rating: 4.8,
      reviewCount: 210,
      stock: 35,
      tags: ["expedition", "65L", "internal frame", "camping"],
      images: ["https://images.unsplash.com/photo-1577733966973-d680bffd2e80?auto=format&fit=crop&w=800&q=80"],
      description: "Heavy expedition trekking rucksack with ergonomic aluminum internal frame, adjustable torso length, and sleeping bag bottom divider.",
      specifications: { "Capacity": "65 Litres + 10L Extension Collar", "Frame": "Dual Contoured Aluminum Stays", "Suspension": "Air-Mesh Breathable Back Panel" },
    },
    {
      name: "Vintage Canvas Leather Daypack",
      cat: "Backpacks",
      brand: "RetroVibe",
      price: 3299,
      mrp: 4199,
      rating: 4.5,
      reviewCount: 390,
      stock: 75,
      tags: ["vintage", "canvas", "genuine leather", "college"],
      images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80"],
      description: "Heavyweight waxed cotton canvas accented with genuine crazy horse leather straps, brass buckles, and magnetic quick snaps.",
      specifications: { "Material": "16oz Heavy Waxed Canvas + Cowhide Leather", "Capacity": "25 Litres", "Laptop Sleeve": 'Fits up to 15.6" Laptop' },
    },
    {
      name: "Slimline Executive Leather Briefcase",
      cat: "Backpacks",
      brand: "ClassicTime",
      price: 6499,
      mrp: 7999,
      rating: 4.7,
      reviewCount: 160,
      stock: 40,
      tags: ["leather", "briefcase", "executive", "business"],
      images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80"],
      description: "Luxurious handcrafted full-grain leather briefcase with detachable shoulder strap and organized business card/pen compartments.",
      specifications: { "Leather": "100% Genuine Full Grain Leather", "Hardware": "Solid Antique Brass", "Laptop Compartment": '14" Padded Slip Pocket' },
    },
    {
      name: "UltraLight Hydration Running Pack",
      cat: "Backpacks",
      brand: "PeakGear",
      price: 2199,
      mrp: 2799,
      rating: 4.4,
      reviewCount: 510,
      stock: 120,
      tags: ["hydration", "marathon", "water bladder", "vest"],
      images: ["https://images.unsplash.com/photo-1609172791772-23f2f5348bb9?auto=format&fit=crop&w=800&q=80"],
      description: "Bounce-free trail running hydration vest includes a 2L BPA-free water bladder with insulated tube and dual front flask pockets.",
      specifications: { "Bladder": "2 Litre Food-Grade TPU Included", "Weight": "280g without water", "Fit": "Dual Adjustable Chest Sternum Straps" },
    },
    {
      name: "CamSafe Camera & Drone Backpack",
      cat: "Backpacks",
      brand: "PeakGear",
      price: 4999,
      mrp: 6299,
      rating: 4.6,
      reviewCount: 290,
      stock: 45,
      tags: ["camera bag", "modular dividers", "side access", "tripod holder"],
      images: ["https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80"],
      description: "Customizable velcro padded dividers securely hold 2 DSLR bodies, 5 lenses, and a foldable drone with quick-draw side zipper access.",
      specifications: { "Dividers": "12 Removable EVA Foam Walls", "Tripod Mount": "External Heavy-Duty Side Straps", "Laptop": '15.6" Dedicated Back Compartment' },
    },
    {
      name: "CampusPro Student Bookbag",
      cat: "Backpacks",
      brand: "CityCarry",
      price: 1299,
      mrp: 1699,
      rating: 4.2,
      reviewCount: 1650,
      stock: 250,
      tags: ["student", "budget", "school", "water bottle pocket"],
      images: ["https://images.unsplash.com/photo-1509762774605-f07235a08f1f?auto=format&fit=crop&w=800&q=80"],
      description: "Classic dual-pocket school bag made with tear-resistant polyester, reinforced dual bottle sleeves, and padded shoulder straps.",
      specifications: { "Capacity": "24 Litres", "Fabric": "Water-Resistant 450D Polyester", "Warranty": "1 Year Replacement Warranty" },
    },
    {
      name: "AquaShield 100% Waterproof DryBag",
      cat: "Backpacks",
      brand: "Trail",
      price: 1899,
      mrp: 2499,
      rating: 4.5,
      reviewCount: 430,
      stock: 130,
      tags: ["waterproof", "dry bag", "kayaking", "roll top"],
      images: ["https://images.unsplash.com/photo-1575844262846-e55543c72bdf?auto=format&fit=crop&w=800&q=80"],
      description: "Roll-top 500D PVC tarpaulin with welded seamless construction keeps gear completely bone dry while rafting, boating, or biking in storms.",
      specifications: { "Waterproof": "IPX6 Heavy Storm & Floating Submersion", "Capacity": "30 Litres", "Seams": "High Frequency Welded (No Stitching)" },
    },
    {
      name: "CrossBody Sling Tactical 10L",
      cat: "Backpacks",
      brand: "CityCarry",
      price: 1599,
      mrp: 2099,
      rating: 4.3,
      reviewCount: 740,
      stock: 140,
      tags: ["sling bag", "crossbody", "tactical", "quick access"],
      images: ["https://images.unsplash.com/photo-1546938576-0e10b1a0e141?auto=format&fit=crop&w=800&q=80"],
      description: "Single-strap reversible crossbody sling backpack with MOLLE webbing and ambidextrous quick-release shoulder buckle.",
      specifications: { "Capacity": "10 Litres", "Tablet Pocket": 'Fits iPad 11" Pro', "Strap": "Reversible Left/Right Padded Sling" },
    },
    {
      name: "MetroRoll Top Urban Waterproof",
      cat: "Backpacks",
      brand: "PeakGear",
      price: 2799,
      mrp: 3499,
      rating: 4.6,
      reviewCount: 380,
      stock: 80,
      tags: ["roll top", "cycling", "urban", "modern"],
      images: ["https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&w=800&q=80"],
      description: "Clean minimalist roll-top closure allows capacity to flex from 18L to 26L with magnetic Fidlock fastener and rear secret card pocket.",
      specifications: { "Closure": "Roll-Top with Aluminum Hook", "Capacity": "18L to 26L Expandable", "Water Resistance": "TPU Coated Waterproof Shell" },
    },
    {
      name: "SolarCharge Smart Commuter Bag",
      cat: "Backpacks",
      brand: "CityCarry",
      price: 3799,
      mrp: 4699,
      rating: 4.4,
      reviewCount: 220,
      stock: 50,
      tags: ["solar panel", "smart backpack", "powerbank", "tech"],
      images: ["https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80"],
      description: "Integrated flexible 7W solar panel charges your smartphone directly from sunlight during outdoor commutes and hikes.",
      specifications: { "Solar Output": "5V 1.4A (7W Max SunPower Cells)", "Laptop Fit": 'Up to 15.6" Laptop', "Capacity": "22 Litres" },
    },
    {
      name: "Weekender Duffel Backpack 45L",
      cat: "Backpacks",
      brand: "PeakGear",
      price: 3499,
      mrp: 4399,
      rating: 4.6,
      reviewCount: 310,
      stock: 65,
      tags: ["duffel", "gym bag", "shoe compartment", "weekend trip"],
      images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80"],
      description: "2-in-1 hybrid gym duffel and travel backpack with hideaway backpack straps, vented shoe compartment, and wet towel pocket.",
      specifications: { "Capacity": "45 Litres", "Converts": "Duffel / Shoulder Bag / Backpack", "Shoe Pocket": "Vented Odor-Resistant Side Tunnel" },
    },
    {
      name: "Minimalist Tech Pack 15L",
      cat: "Backpacks",
      brand: "Aero",
      price: 2299,
      mrp: 2899,
      rating: 4.5,
      reviewCount: 480,
      stock: 90,
      tags: ["minimalist", "slim", "tech pouch", "work"],
      images: ["https://images.unsplash.com/photo-1622560480654-d96214fdc887?auto=format&fit=crop&w=800&q=80"],
      description: "Ultra-slim 12cm depth designed specifically for modern minimalists carrying only a laptop, charger, notebook, and water bottle.",
      specifications: { "Depth": "11.5cm Ultra Slim Profile", "Laptop Sleeve": '14" Padded Neoprene', "Capacity": "15 Litres" },
    },

    /* ============================================================
       8. ACCESSORIES (16 Products)
       ============================================================ */
    {
      name: "ChargeHub 65W GaN",
      cat: "Accessories",
      brand: "ChargeHub",
      price: 1499,
      mrp: 1999,
      rating: 4.4,
      reviewCount: 900,
      stock: 250,
      tags: ["charger", "fast charging", "GaN", "type-c"],
      images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80"],
      description: "ChargeHub 65W GaN fast charger powers laptops, tablets, and phones at full speed with dual USB-C and one USB-A port in a palm-sized build.",
      specifications: { "Total Output": "65W Max GaN III Tech", "Ports": "2x USB-C + 1x USB-A", "Protocols": "PD 3.0, QC 4.0+, PPS Fast Charging", "Dimensions": "5.3 x 5.3 x 3.1 cm" },
    },
    {
      name: "PowerBank 25000mAh 100W PD",
      cat: "Accessories",
      brand: "ChargeHub",
      price: 3999,
      mrp: 4999,
      rating: 4.8,
      reviewCount: 780,
      stock: 140,
      tags: ["powerbank", "100W output", "laptop charger", "flight approved"],
      images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80"],
      description: "High-capacity power bank capable of outputting 100W Power Delivery to charge MacBooks and laptops on flights with smart digital LED display.",
      specifications: { "Capacity": "25,000mAh / 92.5Wh (TSA Approved)", "Output": "100W USB-C PD + 65W USB-C + 18W USB-A", "Display": "Smart TFT Screen (Watts, Volts, Percent)" },
    },
    {
      name: "UltraFast 3-in-1 MagSafe Stand",
      cat: "Accessories",
      brand: "ChargeHub",
      price: 2799,
      mrp: 3599,
      rating: 4.6,
      reviewCount: 420,
      stock: 110,
      tags: ["wireless charger", "magsafe", "desk stand", "3 in 1"],
      images: ["https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=800&q=80"],
      description: "Snap and charge your phone, smartwatch, and earbuds simultaneously with weighted aluminum base and 15W Qi2 fast magnetic charging.",
      specifications: { "Charging Pads": "15W Magnetic Phone + 5W Watch + 5W Earbuds", "Material": "CNC Machined Aluminum + Silicone Pad" },
    },
    {
      name: "Ergonomic Vertical Wireless Mouse",
      cat: "Accessories",
      brand: "Omni",
      price: 1899,
      mrp: 2499,
      rating: 4.5,
      reviewCount: 650,
      stock: 175,
      tags: ["ergonomic", "mouse", "wrist pain relief", "bluetooth"],
      images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80"],
      description: "Natural 57-degree handshake grip posture alleviates carpal tunnel wrist strain, featuring silent click switches and multi-device pairing.",
      specifications: { "DPI": "800 / 1200 / 1600 / 2400 DPI", "Connectivity": "Bluetooth 5.0 + 2.4GHz USB Dongle", "Battery": "Rechargeable 500mAh USB-C" },
    },
    {
      name: "MechKey Pro RGB Mechanical Keyboard",
      cat: "Accessories",
      brand: "Omni",
      price: 4299,
      mrp: 5499,
      rating: 4.7,
      reviewCount: 880,
      stock: 90,
      tags: ["mechanical keyboard", "hot swappable", "RGB", "wireless"],
      images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80"],
      description: "75% compact hot-swappable mechanical keyboard with pre-lubed linear switches, sound dampening silicone gaskets, and south-facing RGB.",
      specifications: { "Switches": "Hot-Swap Gateron Yellow Pre-Lubed", "Layout": "75% Compact 82 Keys", "Modes": "Bluetooth / 2.4GHz / Type-C Wired" },
    },
    {
      name: "USB-C 10-in-1 Dual 4K Hub",
      cat: "Accessories",
      brand: "Omni",
      price: 2999,
      mrp: 3799,
      rating: 4.5,
      reviewCount: 510,
      stock: 130,
      tags: ["docking station", "dual monitor", "100W PD", "gigabit ethernet"],
      images: ["https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=800&q=80"],
      description: "Turn a single USB-C port into dual 4K HDMI outputs, Gigabit Ethernet, 100W PD pass-through, SD card reader, and 3x USB 3.2 ports.",
      specifications: { "Display Out": "Dual 4K @ 60Hz HDMI", "Ethernet": "RJ45 1000 Mbps Gigabit", "Power Delivery": "100W USB-C Pass-through" },
    },
    {
      name: "PureView 4K Ultra HD Webcam",
      cat: "Accessories",
      brand: "Pulse",
      price: 3499,
      mrp: 4499,
      rating: 4.6,
      reviewCount: 390,
      stock: 85,
      tags: ["webcam", "4K", "autofocus", "privacy shutter"],
      images: ["https://images.unsplash.com/photo-1587826080692-f439cd0b70da?auto=format&fit=crop&w=800&q=80"],
      description: "Ultra-sharp 4K 30fps webcam with Sony sensor, dual AI noise-canceling microphones, physical magnetic privacy cover, and auto-framing.",
      specifications: { "Resolution": "4K UHD @ 30fps / 1080p @ 60fps", "FOV": "90-Degree Wide Angle Lens", "Microphone": "Stereo Dual AI Beamforming Mics" },
    },
    {
      name: "StudioCard 2TB NVMe Portable SSD",
      cat: "Accessories",
      brand: "Omni",
      price: 8999,
      mrp: 10999,
      rating: 4.8,
      reviewCount: 620,
      stock: 70,
      tags: ["portable SSD", "2TB", "1050MB/s", "drop resistant"],
      images: ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80"],
      description: "Blazing fast read/write speeds up to 1,050 MB/s encased in IP55 water/dust resistant rubberized aluminum with 256-bit AES encryption.",
      specifications: { "Speed": "Up to 1,050 MB/s Read & 1,000 MB/s Write", "Durability": "IP55 Water/Dust + 2m Drop Resistance", "Interface": "USB 3.2 Gen 2 Type-C" },
    },
    {
      name: "ArmorShield Tempered Glass Pack",
      cat: "Accessories",
      brand: "Omni",
      price: 499,
      mrp: 799,
      rating: 4.3,
      reviewCount: 3200,
      stock: 500,
      tags: ["screen protector", "9H hardness", "oleophobic", "easy install"],
      images: ["https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80"],
      description: "9H diamond hardness shatterproof tempered glass 2-pack with auto-alignment installation frame and anti-fingerprint oleophobic coating.",
      specifications: { "Hardness": "9H Scratch Resistant", "Thickness": "0.33mm Ultra-Thin", "Kit Includes": "2x Glass + Alignment Frame + Cleaning Kits" },
    },
    {
      name: "CarbonFiber Laptop Stand Ergonomic",
      cat: "Accessories",
      brand: "Omni",
      price: 1299,
      mrp: 1799,
      rating: 4.5,
      reviewCount: 940,
      stock: 160,
      tags: ["laptop stand", "aluminum", "heat dissipation", "collapsible"],
      images: ["https://images.unsplash.com/photo-1616353071855-2c045c4458ae?auto=format&fit=crop&w=800&q=80"],
      description: "Fully adjustable height and angle aluminum desk riser promoting ideal eye-level posture while optimizing bottom cooling airflow.",
      specifications: { "Material": "Sandblasted Anodized Aluminum", "Adjustment": "6 Adjustable Height Angles (15° to 45°)", "Compatibility": '10" to 17.3" Laptops' },
    },
    {
      name: "CableArmor Braided Type-C 2m Kit",
      cat: "Accessories",
      brand: "ChargeHub",
      price: 699,
      mrp: 999,
      rating: 4.6,
      reviewCount: 1800,
      stock: 400,
      tags: ["type-c cable", "100W PD", "braided nylon", "durable"],
      images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80"],
      description: "Heavy-duty double-braided nylon 100W E-marker fast charge cables tested to withstand 30,000+ bends without fraying.",
      specifications: { "Power": "100W (20V/5A) Power Delivery with E-Marker", "Length": "2 Meters (6.6 Feet)", "Data Transfer": "480 Mbps" },
    },
    {
      name: "AuraGlow RGB Desk Mat XL",
      cat: "Accessories",
      brand: "Omni",
      price: 999,
      mrp: 1499,
      rating: 4.4,
      reviewCount: 1100,
      stock: 220,
      tags: ["desk mat", "mousepad", "RGB lighting", "micro-weave"],
      images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80"],
      description: "Massive 900x400mm micro-woven cloth surface with 14 customizable RGB perimeter lighting modes and non-slip rubber base.",
      specifications: { "Size": "900 x 400 x 4 mm", "Lighting": "14 LED Modes (7 Static Colors + Breathing + Waves)", "Surface": "Spill-Proof Micro-Texture Fabric" },
    },
    {
      name: "StreamerCard 4K60 Capture Card",
      cat: "Accessories",
      brand: "Omni",
      price: 4999,
      mrp: 6499,
      rating: 4.7,
      reviewCount: 310,
      stock: 60,
      tags: ["capture card", "OBS", "twitch", "console streaming"],
      images: ["https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80"],
      description: "Zero-latency 4K60 HDR passthrough with crystal clear 1080p 60fps capture for console and camera live streaming to Twitch and YouTube.",
      specifications: { "Passthrough": "4K @ 60Hz HDR / 1440p @ 144Hz Zero Lag", "Capture": "1080p @ 60fps NV12 / YUY2", "Compatibility": "OBS, Streamlabs, Discord, Zoom" },
    },
    {
      name: "SmartTracker Bluetooth Key Tag 4-Pack",
      cat: "Accessories",
      brand: "Omni",
      price: 1999,
      mrp: 2699,
      rating: 4.3,
      reviewCount: 850,
      stock: 180,
      tags: ["smart tag", "key finder", "anti lost", "water resistant"],
      images: ["https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80"],
      description: "Locate misplaced keys, bags, and luggage with ultra-loud 90dB buzzer chime and crowd GPS tracking network on iOS/Android.",
      specifications: { "Pack": "4 Tags Included (Black/White/Blue/Red)", "Battery": "CR2032 User Replaceable (1 Year Life)", "Sound": "90dB High-Pitch Speaker" },
    },
    {
      name: "SoundBeam Desktop Soundbar Bluetooth",
      cat: "Accessories",
      brand: "SonicWave",
      price: 2499,
      mrp: 3299,
      rating: 4.4,
      reviewCount: 670,
      stock: 100,
      tags: ["soundbar", "desktop speaker", "bluetooth", "AUX"],
      images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80"],
      description: "Sleek low-profile under-monitor soundbar with dual passive bass radiators, Bluetooth 5.3, USB audio, and AUX input.",
      specifications: { "Output Power": "20W Peak (10W RMS Dual Drivers)", "Inputs": "Bluetooth 5.3, USB-Audio, 3.5mm AUX", "Lighting": "Dynamic Ambient Base Glow" },
    },
    {
      name: "CarMount MagSafe AirVent Qi 15W",
      cat: "Accessories",
      brand: "ChargeHub",
      price: 1399,
      mrp: 1899,
      rating: 4.5,
      reviewCount: 920,
      stock: 210,
      tags: ["car mount", "magsafe", "wireless car charger", "air vent"],
      images: ["https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"],
      description: "Powerful N52 neodymium magnets hold your phone rock-steady over speed bumps with 15W fast wireless Qi charging and 360 rotation.",
      specifications: { "Magnets": "16x Strong N52 Neodymium Array", "Mount": "Hook-Lock Steel Air Vent Clamp", "Power": "15W Fast Qi Magnetic Charge" },
    },
  ];

  const productIds: string[] = [];
  let updatedCount = 0;
  let insertedCount = 0;

  for (const p of PRODUCTS) {
    const existing = await db.query.products.findFirst({ where: (row, { eq }) => eq(row.name, p.name) });
    if (existing) {
      // Update existing product — always stamp businessId so re-runs fix ownership
      await db.update(schema.products)
        .set({
          ...(businessId ? { businessId } : {}),
          images: p.images,
          description: p.description ?? existing.description,
          specifications: p.specifications ?? existing.specifications,
          updatedAt: new Date(),
        })
        .where(eq(schema.products.id, existing.id));
      productIds.push(existing.id);
      updatedCount++;
      continue;
    }

    const [row] = await db.insert(schema.products).values({
      businessId,
      categoryId: categoryIds[p.cat],
      name: p.name,
      brand: p.brand,
      description: p.description || `${p.name} — a ${p.cat.toLowerCase()} built for ${p.tags[0]}.`,
      price: String(p.price),
      mrp: String(p.mrp),
      rating: String(p.rating),
      reviewCount: p.reviewCount,
      stock: p.stock,
      tags: p.tags,
      images: p.images,
      specifications: p.specifications || {},
    }).returning();
    productIds.push(row.id);
    insertedCount++;
  }
  console.log(`Products: ${updatedCount} updated, ${insertedCount} newly inserted. Total catalog: ${productIds.length}`);

  // If we have a businessId, make sure ALL products in the catalog have it set.
  // This covers the case where products were seeded before any business existed.
  if (businessId) {
    const { isNull } = await import("drizzle-orm");
    const nullBizProducts = await db.query.products.findMany({
      where: isNull(schema.products.businessId),
    });
    if (nullBizProducts.length > 0) {
      await db.update(schema.products)
        .set({ businessId })
        .where(isNull(schema.products.businessId));
      console.log(`Assigned businessId to ${nullBizProducts.length} products that had no owner.`);
    }
  }

  const allBusinesses = await db.query.businesses.findMany();
  if (allBusinesses.length > 0) {
    console.log(`Seeding demo customers, segments, campaigns, and insights for ${allBusinesses.length} business(es)...`);
    const customerDefs = [
      { name: "Meera Reddy", score: 88, seg: "vip" as const, spend: 48200 },
      { name: "Kabir Shah", score: 76, seg: "loyal" as const, spend: 29900 },
      { name: "Anaya Gupta", score: 63, seg: "high_intent" as const, spend: 8400 },
      { name: "Rohan Verma", score: 34, seg: "at_risk" as const, spend: 15600 },
      { name: "Priya Nair", score: 22, seg: "cart_abandoner" as const, spend: 0 },
      { name: "Devika Rao", score: 91, seg: "vip" as const, spend: 61200 },
    ];

    for (const b of allBusinesses) {
      for (const c of customerDefs) {
        const existing = await db.query.customers.findFirst({
          where: (row, { and, eq }) => and(eq(row.businessId, b.id), eq(row.displayName, c.name)),
        });
        if (existing) continue;
        const [customer] = await db.insert(schema.customers).values({
          businessId: b.id, displayName: c.name, aiScore: c.score, lifetimeSpend: String(c.spend),
        }).returning();
        await db.insert(schema.customerSegments).values({ customerId: customer.id, segment: c.seg });
      }

      const insightExists = await db.query.aiInsights.findFirst({ where: (row, { eq }) => eq(row.businessId, b.id) });
      if (!insightExists) {
        await db.insert(schema.aiInsights).values([
          { businessId: b.id, title: "Recover Abandoned Carts", description: "342 carts abandoned in the last 30 days, avg value ₹13,400.", impact: "high", effort: "low", potentialRevenue: "180000" },
          { businessId: b.id, title: "Bundle Headphones with Phones", description: "Cross-sell opportunity based on co-purchase patterns.", impact: "medium", effort: "medium", potentialRevenue: "64000" },
          { businessId: b.id, title: "Re-engage VIP segment", description: "6 VIP customers haven't purchased in 30+ days.", impact: "medium", effort: "low", potentialRevenue: "92000" },
        ]);
      }

      const campaignExists = await db.query.campaigns.findFirst({ where: (row, { eq }) => eq(row.businessId, b.id) });
      if (!campaignExists) {
        await db.insert(schema.campaigns).values([
          { businessId: b.id, name: "Abandoned Cart Recovery", status: "active", targetSegment: "cart_abandoner", offer: "10% off", sentCount: 342, recoveredRevenue: "120000", conversionRate: "14.2" },
          { businessId: b.id, name: "VIP Early Access — New Laptops", status: "scheduled", targetSegment: "vip", offer: "Early access" },
        ]);
      }
    }
  }

  console.log(`Done. Seeded ${categoryDefs.length} categories and ${productIds.length} products.`);
  await sql.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
